name: Gradle Build and Publish Artifacts

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4.0.0
    - name: Make gradlew executable
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Capture build artifacts
      run: |
        # 创建 artifacts 目录
        mkdir -p artifacts
        
        # 复制主要的构建产物
        find . -name "*.jar" -not -path "*/build/libs/*" -exec cp {} artifacts/ \;
        find . -name "*-all.jar" -exec cp {} artifacts/ \;
        find . -name "*-SNAPSHOT.jar" -exec cp {} artifacts/ \;
        
        # 复制 libs 目录下的所有 jar 文件
        find . -path "*/build/libs/*.jar" -exec cp {} artifacts/ \;
        
        # 复制其他可能需要的文件
        cp -r build/reports artifacts/reports || true
        cp -r build/docs artifacts/docs || true
        
        # 列出所有收集的文件
        ls -la artifacts/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: artifacts/
        retention-days: 30

    # 可选：发布到 GitHub Packages（如果需要）
    - name: Publish to GitHub Packages
      if: github.event_name == 'release'
      run: ./gradlew publish
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
